### ISSUE TITLE
Incompatible with SDV 1.4

### ISSUE THREAD

**Issue by RnDMonkey** [aEnigmatic/StardewValley#5]
Does not work in Stardew Valley 1.4 with the following SMAPI trace:
[11:17:01 TRACE SMAPI]    Convenient Chests (from Mods\ConvenientChests\ConvenientChests.dll)...
[11:17:01 TRACE SMAPI]       Rewriting ConvenientChests.dll for OS...
[11:17:01 TRACE SMAPI]       Broken code in ConvenientChests.dll: reference to StardewValley.ISoundBank.GetCue (no such method).
[11:17:01 TRACE SMAPI]       Detected game patcher (Harmony.HarmonyInstance type) in assembly ConvenientChests.dll.
[11:17:01 TRACE SMAPI]       Broken code in ConvenientChests.dll: reference to StardewValley.Farmer.recipesCooked (field returns StardewValley.Network.NetIntDictionary`2<System.Int32,Netcode.NetInt>, not StardewValley.SerializableDictionary`2<System.Int32,System.Int32>).
[11:17:01 TRACE SMAPI]       Broken code in ConvenientChests.dll: reference to StardewValley.Game1.dailyLuck (no such field).
[11:17:01 TRACE SMAPI]       Broken code in ConvenientChests.dll: reference to StardewValley.Item.canStackWith (no such method).
[11:17:01 TRACE SMAPI]       Broken code in ConvenientChests.dll: reference to StardewValley.Item.addToStack (no such method).
[11:17:01 TRACE SMAPI]       Broken code in ConvenientChests.dll: reference to StardewValley.Item.drawInMenu (no such method).
[11:17:01 TRACE SMAPI]       Loading ConvenientChests.dll (rewritten in memory)...

**Comment by aEnigmatic** [comment]
Fixed with  826197a.
